/*Assignment 2, Adrianna Pops, DSCI 604 Asynchronous*/

/*1. Add a new customer to the customer table*/
INSERT INTO customer(`store_id`, `first_name`, `last_name`, `email`, `address_id`, `active`)
VALUES(1, 'John','Doe','john.doe@example.com', 1, 1);
SELECT store_id, first_name, last_name, email, active FROM customer;
/*2. Insert a new record into the film table*/
SELECT * FROM film;

INSERT INTO film(`title`, `description`, `release_year`, `language_id`, `rental_duration`, `rental_rate`, `replacement_cost`)
VALUES('Code Masters', 'A movie about the world of coding', 2024, 1, 7, '2.99', '19.99');

/*3. Add a new record to the actor table*/
SELECT * FROM actor;

INSERT INTO actor(`first_name`, `last_name`)
VALUES('Emily', 'Blunt');

/*4. Retrieve first name, last name, and email from all active customers*/
SELECT first_name, last_name, email FROM customer;

/*5. List the titles of films rented by the customer with ID 3.*/
SELECT f.title FROM film f
	JOIN inventory i ON f.film_id = i.film_id
	JOIN rental r ON i.inventory_id = r.inventory_id
		WHERE r.customer_id = 3;

/*6. Find all films with "Adventure" in their description. Display the title, description, and release year.*/
SELECT title, description, release_year FROM  film
	WHERE description LIKE '%Adventure%';
    
/*7. For all films with a rental rate less than 2.00, increase the rental rate by 0.50.*/
SELECT title, rental_rate+0.50
	FROM film
		WHERE rental_rate < 2.00;
	
/*8. Delete the film titled "Code Masters" that you created earlier in the assignment.*/
DELETE FROM film
    WHERE title = 'Code Masters';
    
/*9. Remove all records from the rental table where the rental date is more than 5 years old.*/
DELETE FROM rental
	WHERE rental_date < CURDATE();
    
/*10. Retrieve the title and description of all films released in the year 2006.*/
SELECT title, description FROM  film
	WHERE release_year = 2006;
    
/*11. Display the first_name, last_name, and email of all customers who have no rentals in the rental table.*/
SELECT c.first_name, c.last_name, c.email FROM customer c
	LEFT JOIN rental r ON c.customer_id = r.customer_id
    WHERE r.rental_id IS NULL;

/*12. Find the total number of films for each category. Display the category name and the film count.*/
SELECT c.name AS category_name, COUNT(f.film_id) AS film_count FROM category c
	JOIN film_category fc ON c.category_id = fc.category_id
    JOIN film f ON fc.film_id = f.film_id
    GROUP BY c.name;

/*13. Calculate the total revenue generated by each store. Display the store id and the total revenue.*/
SELECT s.store_id, SUM(p.amount) AS total_rev FROM payment p
	JOIN staff st ON p.staff_id = st.staff_id
    JOIN store s ON st.store_id = s.store_id
    GROUP BY s.store_id