-- EMPLOYEE TABLE FROM PROJECT 5
-- Create this table by copying any 10 rows from the table you created in project 5
-- using “create table from an existing table” technique. 

DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE (
  id INTEGER(10),
  first_name VARCHAR(10),
  last_name VARCHAR(10),
  email VARCHAR(20),
  emp_pass VARCHAR(15),
  salary INTEGER
);

CREATE SEQUENCE emp_id INCREMENT BY 1 START WITH 1;

DECLARE
 id INTEGER(10);
 fname VARCHAR(10);
 lname VARCHAR(10);
 stremail VARCHAR(20);
 epwd VARCHAR(15);
 sal INTEGER;

BEGIN
id := emp_id.NEXTVAL;

FOR i IN 1 ..500 LOOP
 fname := DBMS_RANDOM.string('u', ROUND(DBMS_RANDOM.value(1,10)));
 lname := DBMS_RANDOM.string('u', ROUND(DBMS_RANDOM.value(1,10)));
 stremail := DBMS_RANDOM.string('1',10)||'@'||DBMS_RANDOM.string('1',5)||'.'||DBMS_RANDOM.string('2',3);
 epwd := DBMS_RANDOM.string('x', ROUND(DBMS_RANDOM.value(8,15)));
 sal := ROUND(DBMS_RANDOM.value(low => 1, high => 100000));

INSERT INTO EMPLOYEE VALUES(i, fname, lname, stremail, epwd, sal);
END LOOP;
END;
/

SELECT *
FROM EMPLOYEE;

-- STEP 1 // Create the BBT_USERS_TEMP table (10'). 
CREATE TABLE BBT_USERS_TEMP AS
	(SELECT* FROM EMPLOYEE WHERE ROWNUM<=10);

SELECT *
FROM BBT_USERS_TEMP;

--STEP 2 // Create PHONE_USERS table (10’)
CREATE OR REPLACE TABLE PHONE_USERS(
TELEPHONE_NUMBER VARCHAR(80) PRIMARY KEY, 
FIRST NAME VARCHAR(80), 
KEYMAP_LASTNAME VARCHAR(4) UNIQUE, 
PASSWORD VARCHAR(80)
);

SELECT *
FROM PHONE_USERS;

-- STEP 3 // Create function(20’)
CREATE OR REPLACE FUNCTION KEYMAP(LASTNAME IN VARCHAR2)
RETURN VARCHAR2
IS
	EXTENSION VARCHAR2(4);

-- Use translate function to convert the lastname to extension
BEGIN
	EXTENSION:= TRANSLATE(EXTENSION,'ABC','222');
	EXTENSION:= TRANSLATE(EXTENSION,'DEF','333');
	EXTENSION:= TRANSLATE(EXTENSION,'GHI','444');
	EXTENSION:= TRANSLATE(EXTENSION,'JKL','555');
	EXTENSION:= TRANSLATE(EXTENSION,'MNO','666');
	EXTENSION:= TRANSLATE(EXTENSION,'PQRS','7777');
	EXTENSION:= TRANSLATE(EXTENSION,'TUV','888');
	EXTENSION:= TRANSLATE(EXTENSION,'WXYZ','9999');

	-- for names shorter than 4 characters, then use zeros as placeholders
	IF LENGTH(LASTNAME)<4 THEN
		FOR VAR IN 1..(4-LENGTH(LASTNAME))
		LOOP
			EXTENSION:= || '0';
		END LOOP;
	END IF;
END;
/

-- test
BEGIN
	EXTENSION:= KEYMAP('Pops');
	DBMS OUTPUT.PUT LINE('EXTENSION ' I || EXTENSION);
	EXTENSION:= KEYMAP('Pi");
	DBMS OUTPUT.PUT LINE('EXTENSION ' I || EXTENSION);
END;

-- STEP 4 // create procedure  (35’)
CREATE OR REPLACE PROCEDURE SPPUSERS 
(N IN NUMBER, TELE IN VARCHAR)
IS

BEGIN
DECLARE
A NUMBER:= 1;
I NUMBER:= 1;
TELE VARCHAR(50);
FIRSTNAME VARCHAR(50);
LASTNAME VARCHAR(50);
PASSWORD VARCHAR (50);

FOR A IN 1..N LOOP
	FIRSTNAME:= (SELECT first_name FROM BBT_USERS_TEMP WHERE ROW_NUMBER()= I);
	LASTNAME:= (SELECT last_name FROM BBT_USERS_TEMP WHERE ROW_NUMBER()= I);
	PASSWORD:= (SELECT emp_pass FROM BBT_USERS_TEMP WHERE ROW_NUMBER()= I);

	INSERT INTO PHONE_USERS
		VALUES(TELE, FIRSTNAME, LASTNAME, PASSWORD);

	I:= I + 1;
END LOOP;
END;
/

-- STEP 5 // Create package (20’)
CREATE OR REPLACE PACKAGE USER_ACTIONS AS
	PROCEDURE SPPUSERS('(111) 222-3344', 5);
END USER_ACTIONS;

-- STEP 6 // Run the programs in the package to test. (5’)
EXECUTE SPPUSERS;
