SELECT *
FROM AUTHOR
WHERE AUTHORNAME = 'Irving' ;

SELECT *
FROM BOOK_ORDER, AUTHOR
WHERE TITLE LIKE 'A%'
(SELECT AUTHORNAME
    FROM AUTHOR
    WHERE AUTHORNAME = 'Green');

SELECT *
FROM LOCATION
WHERE CITY IN ('UK');

SELECT *
FROM WEATHER
WHERE City='Indianapolis' AND Condition='Humid';

SELECT *
FROM WEATHER
WHERE Temperature='60' OR Condition='Rainy';

SELECT AUTHORNAME, COMMENTS
FROM AUTHOR
WHERE COMMENTS IS NOT NULL;

SELECT *
FROM GAMER_RATING
ORDER BY SCORE ASC;

SELECT *
FROM BOOKSHELF_AUTHOR
ORDER BY AUTHORNAME DESC;

SELECT TITLE, AUDIT_DATE, NEW_RATING
FROM BOOKSHELF_AUDIT
WHERE AUDIT_DATE > '12/21/2021';

SELECT TITLE, PUBLISHER
FROM BOOK_ORDER
INNER JOIN BOOK_ORDER ON BOOKSHELF_AUTHOR.TITLE=BOOK_ORDER.TITLE;

CREATE VIEW pops_project2_view AS
SELECT *
FROM BOOK_ORDER, AUTHOR
WHERE TITLE LIKE 'A%' OR AUTHORNAME= 'Irving'
ORDER BY AUTHORNAME DESC;

